<a href="https://colab.research.google.com/github/flash-jaehyun/excel_modification_friends/blob/main/saving_private_seungwoo_20210312.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install xlrd
!pip install openpyxl
!pip install pandas

Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.7/dist-packages (2.5.9)
Requirement already satisfied: jdcal in /usr/local/lib/python3.7/dist-packages (from openpyxl) (1.4.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl) (1.0.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [3]:
import pandas as pd
xlsx = pd.read_excel('raw.xlsx')
xlsx.to_csv("raw.csv")

KeyboardInterrupt: ignored

In [4]:
ls

raw.csv  raw.xlsx  sample_data/

In [5]:
import csv
import numpy as np
#import pandas as pd

In [6]:
# 파일 이름 수정해주기
f = open('raw.csv', 'r')
rdr = csv.reader(f)
raw = []
for line in rdr:
    raw.append(line)
f.close()

In [7]:
진입일 = [];
진입시간 = [];
방향 = [];
차선 = [];
속도 = [];
총중량 = [];
번호 = [];
차종 = [];
차량번호 = [];
축중량1 = [];
축중량2 = [];
축중량3 = [];
축중량4 = [];
축중량5 = [];
축중량6 = [];
축중량7 = [];
축중량8 = [];
#NaN or 0
소속 = [];
화물 = [];
주행결과 = [];
공차중량 = [];
적재중량 = [];

size = len(raw);

In [10]:
for i in range(1,size):
    del raw[i][0]
    if  int(raw[i][16]) == 0:
        진입일.append(str(raw[i][0])[0:4]+'-'+str(raw[i][0])[4:6]+'-'+str(raw[i][0])[6:8])
        진입시간.append(str(raw[i][0])[8:10]+':'+str(raw[i][0])[10:12]+':'+str(raw[i][0])[12:14])
        방향.append(str(raw[i][1][0:2]))
        차선.append(str(raw[i][1][2]))
        속도.append((int(raw[i][6]))/100)
        번호.append(int(i))
        차종.append(str(raw[i][4][:-2]))
        차량번호.append(str(raw[i][3]))
        축중량1.append((int(raw[i][9]))/100)
        축중량2.append((int(raw[i][10]))/100)
        축중량3.append((int(raw[i][11]))/100)
        축중량4.append((int(raw[i][12]))/100)
        축중량5.append((int(raw[i][13]))/100)
        축중량6.append((int(raw[i][14]))/100)
        축중량7.append((int(raw[i][15]))/100)
        축중량8.append((int(raw[i][16]))/100)
        총중량.append((int(raw[1][8][:-2])-int(raw[1][16]))/100)

        # NaN
        소속.append(np.NaN)
        화물.append(np.NaN)
        주행결과.append(np.NaN)
        공차중량.append(np.NaN)
        적재중량.append(np.NaN)
    else:
        print(i)

16864
72066
80891
143652

In [11]:
df = pd.DataFrame({'No':번호, '소속':소속,'방향':방향, '화물':화물, '차선':차선 ,'진입일':진입일, '진입시간':진입시간, '차종':차종, '차량번호':차량번호, '주행결과':주행결과, '속도':속도, '총중량':총중량, '공차중량':공차중량, '적재중량':적재중량, '1축중량':축중량1,'2축중량':축중량2,'3축중량':축중량3,'4축중량':축중량4,'5축중량':축중량5, '6축중량':축중량6, '7축중량':축중량7, '8축중량':축중량8 })

In [12]:
df

            No  소속  방향  화물 차선         진입일  ...  3축중량 4축중량  5축중량  6축중량  7축중량  8축중량
0            1 NaN  하행 NaN  2  2020-04-01  ...  9.59  9.5  7.22   0.0   0.0   0.0
1            2 NaN  하행 NaN  2  2020-04-01  ...  0.00  0.0  0.00   0.0   0.0   0.0
2            3 NaN  하행 NaN  2  2020-04-01  ...  0.00  0.0  0.00   0.0   0.0   0.0
3            4 NaN  하행 NaN  2  2020-04-01  ...  4.55  0.0  0.00   0.0   0.0   0.0
4            5 NaN  하행 NaN  1  2020-04-01  ...  0.00  0.0  0.00   0.0   0.0   0.0
...        ...  ..  ..  .. ..         ...  ...   ...  ...   ...   ...   ...   ...
155630  155635 NaN  하행 NaN  1  2020-04-17  ...  0.00  0.0  0.00   0.0   0.0   0.0
155631  155636 NaN  하행 NaN  1  2020-04-17  ...  4.46  0.0  0.00   0.0   0.0   0.0
155632  155637 NaN  하행 NaN  1  2020-04-17  ...  0.00  0.0  0.00   0.0   0.0   0.0
155633  155638 NaN  하행 NaN  1  2020-04-17  ...  0.00  0.0  0.00   0.0   0.0   0.0
155634  155639 NaN  하행 NaN  2  2020-04-17  ...  0.00  0.0  0.00   0.0   0.0   0.0

[155635 rows x 22 columns]

In [13]:
df.to_excel('modified.xlsx')